dir: gops/mocks
structname: Mock{{.InterfaceName}}
pkgname: mocks
filename: 'mock_{{.InterfaceName | snakecase}}.go'
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/AvengeMedia/dgop/gops:
    interfaces:
      CPUInfoProvider: {}
      DiskInfoProvider: {}
      FileSystem: {}
      HostInfoProvider: {}
      LoadInfoProvider: {}
      MemoryInfoProvider: {}
      NetworkInfoProvider: {}
      ProcessInfoProvider: {}
