// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	"github.com/shirou/gopsutil/v4/cpu"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCPUInfoProvider creates a new instance of MockCPUInfoProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCPUInfoProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCPUInfoProvider {
	mock := &MockCPUInfoProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCPUInfoProvider is an autogenerated mock type for the CPUInfoProvider type
type MockCPUInfoProvider struct {
	mock.Mock
}

type MockCPUInfoProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCPUInfoProvider) EXPECT() *MockCPUInfoProvider_Expecter {
	return &MockCPUInfoProvider_Expecter{mock: &_m.Mock}
}

// Counts provides a mock function for the type MockCPUInfoProvider
func (_mock *MockCPUInfoProvider) Counts(logical bool) (int, error) {
	ret := _mock.Called(logical)

	if len(ret) == 0 {
		panic("no return value specified for Counts")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(bool) (int, error)); ok {
		return returnFunc(logical)
	}
	if returnFunc, ok := ret.Get(0).(func(bool) int); ok {
		r0 = returnFunc(logical)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(bool) error); ok {
		r1 = returnFunc(logical)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCPUInfoProvider_Counts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Counts'
type MockCPUInfoProvider_Counts_Call struct {
	*mock.Call
}

// Counts is a helper method to define mock.On call
//   - logical bool
func (_e *MockCPUInfoProvider_Expecter) Counts(logical any) *MockCPUInfoProvider_Counts_Call {
	return &MockCPUInfoProvider_Counts_Call{Call: _e.mock.On("Counts", logical)}
}

func (_c *MockCPUInfoProvider_Counts_Call) Run(run func(logical bool)) *MockCPUInfoProvider_Counts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCPUInfoProvider_Counts_Call) Return(n int, err error) *MockCPUInfoProvider_Counts_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockCPUInfoProvider_Counts_Call) RunAndReturn(run func(logical bool) (int, error)) *MockCPUInfoProvider_Counts_Call {
	_c.Call.Return(run)
	return _c
}

// Info provides a mock function for the type MockCPUInfoProvider
func (_mock *MockCPUInfoProvider) Info() ([]cpu.InfoStat, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Info")
	}

	var r0 []cpu.InfoStat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]cpu.InfoStat, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []cpu.InfoStat); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]cpu.InfoStat)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCPUInfoProvider_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockCPUInfoProvider_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
func (_e *MockCPUInfoProvider_Expecter) Info() *MockCPUInfoProvider_Info_Call {
	return &MockCPUInfoProvider_Info_Call{Call: _e.mock.On("Info")}
}

func (_c *MockCPUInfoProvider_Info_Call) Run(run func()) *MockCPUInfoProvider_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCPUInfoProvider_Info_Call) Return(infoStats []cpu.InfoStat, err error) *MockCPUInfoProvider_Info_Call {
	_c.Call.Return(infoStats, err)
	return _c
}

func (_c *MockCPUInfoProvider_Info_Call) RunAndReturn(run func() ([]cpu.InfoStat, error)) *MockCPUInfoProvider_Info_Call {
	_c.Call.Return(run)
	return _c
}

// Percent provides a mock function for the type MockCPUInfoProvider
func (_mock *MockCPUInfoProvider) Percent(interval time.Duration, perCPU bool) ([]float64, error) {
	ret := _mock.Called(interval, perCPU)

	if len(ret) == 0 {
		panic("no return value specified for Percent")
	}

	var r0 []float64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(time.Duration, bool) ([]float64, error)); ok {
		return returnFunc(interval, perCPU)
	}
	if returnFunc, ok := ret.Get(0).(func(time.Duration, bool) []float64); ok {
		r0 = returnFunc(interval, perCPU)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(time.Duration, bool) error); ok {
		r1 = returnFunc(interval, perCPU)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCPUInfoProvider_Percent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Percent'
type MockCPUInfoProvider_Percent_Call struct {
	*mock.Call
}

// Percent is a helper method to define mock.On call
//   - interval time.Duration
//   - perCPU bool
func (_e *MockCPUInfoProvider_Expecter) Percent(interval any, perCPU any) *MockCPUInfoProvider_Percent_Call {
	return &MockCPUInfoProvider_Percent_Call{Call: _e.mock.On("Percent", interval, perCPU)}
}

func (_c *MockCPUInfoProvider_Percent_Call) Run(run func(interval time.Duration, perCPU bool)) *MockCPUInfoProvider_Percent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Duration
		if args[0] != nil {
			arg0 = args[0].(time.Duration)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCPUInfoProvider_Percent_Call) Return(float64s []float64, err error) *MockCPUInfoProvider_Percent_Call {
	_c.Call.Return(float64s, err)
	return _c
}

func (_c *MockCPUInfoProvider_Percent_Call) RunAndReturn(run func(interval time.Duration, perCPU bool) ([]float64, error)) *MockCPUInfoProvider_Percent_Call {
	_c.Call.Return(run)
	return _c
}

// Times provides a mock function for the type MockCPUInfoProvider
func (_mock *MockCPUInfoProvider) Times(perCPU bool) ([]cpu.TimesStat, error) {
	ret := _mock.Called(perCPU)

	if len(ret) == 0 {
		panic("no return value specified for Times")
	}

	var r0 []cpu.TimesStat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(bool) ([]cpu.TimesStat, error)); ok {
		return returnFunc(perCPU)
	}
	if returnFunc, ok := ret.Get(0).(func(bool) []cpu.TimesStat); ok {
		r0 = returnFunc(perCPU)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]cpu.TimesStat)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(bool) error); ok {
		r1 = returnFunc(perCPU)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCPUInfoProvider_Times_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Times'
type MockCPUInfoProvider_Times_Call struct {
	*mock.Call
}

// Times is a helper method to define mock.On call
//   - perCPU bool
func (_e *MockCPUInfoProvider_Expecter) Times(perCPU any) *MockCPUInfoProvider_Times_Call {
	return &MockCPUInfoProvider_Times_Call{Call: _e.mock.On("Times", perCPU)}
}

func (_c *MockCPUInfoProvider_Times_Call) Run(run func(perCPU bool)) *MockCPUInfoProvider_Times_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCPUInfoProvider_Times_Call) Return(timesStats []cpu.TimesStat, err error) *MockCPUInfoProvider_Times_Call {
	_c.Call.Return(timesStats, err)
	return _c
}

func (_c *MockCPUInfoProvider_Times_Call) RunAndReturn(run func(perCPU bool) ([]cpu.TimesStat, error)) *MockCPUInfoProvider_Times_Call {
	_c.Call.Return(run)
	return _c
}
