// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	cpu "github.com/shirou/gopsutil/v4/cpu"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockCPUInfoProvider is an autogenerated mock type for the CPUInfoProvider type
type MockCPUInfoProvider struct {
	mock.Mock
}

type MockCPUInfoProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCPUInfoProvider) EXPECT() *MockCPUInfoProvider_Expecter {
	return &MockCPUInfoProvider_Expecter{mock: &_m.Mock}
}

// Counts provides a mock function with given fields: logical
func (_m *MockCPUInfoProvider) Counts(logical bool) (int, error) {
	ret := _m.Called(logical)

	if len(ret) == 0 {
		panic("no return value specified for Counts")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(bool) (int, error)); ok {
		return rf(logical)
	}
	if rf, ok := ret.Get(0).(func(bool) int); ok {
		r0 = rf(logical)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(bool) error); ok {
		r1 = rf(logical)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCPUInfoProvider_Counts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Counts'
type MockCPUInfoProvider_Counts_Call struct {
	*mock.Call
}

// Counts is a helper method to define mock.On call
//   - logical bool
func (_e *MockCPUInfoProvider_Expecter) Counts(logical interface{}) *MockCPUInfoProvider_Counts_Call {
	return &MockCPUInfoProvider_Counts_Call{Call: _e.mock.On("Counts", logical)}
}

func (_c *MockCPUInfoProvider_Counts_Call) Run(run func(logical bool)) *MockCPUInfoProvider_Counts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool))
	})
	return _c
}

func (_c *MockCPUInfoProvider_Counts_Call) Return(_a0 int, _a1 error) *MockCPUInfoProvider_Counts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCPUInfoProvider_Counts_Call) RunAndReturn(run func(bool) (int, error)) *MockCPUInfoProvider_Counts_Call {
	_c.Call.Return(run)
	return _c
}

// Info provides a mock function with no fields
func (_m *MockCPUInfoProvider) Info() ([]cpu.InfoStat, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Info")
	}

	var r0 []cpu.InfoStat
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]cpu.InfoStat, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []cpu.InfoStat); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]cpu.InfoStat)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCPUInfoProvider_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockCPUInfoProvider_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
func (_e *MockCPUInfoProvider_Expecter) Info() *MockCPUInfoProvider_Info_Call {
	return &MockCPUInfoProvider_Info_Call{Call: _e.mock.On("Info")}
}

func (_c *MockCPUInfoProvider_Info_Call) Run(run func()) *MockCPUInfoProvider_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCPUInfoProvider_Info_Call) Return(_a0 []cpu.InfoStat, _a1 error) *MockCPUInfoProvider_Info_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCPUInfoProvider_Info_Call) RunAndReturn(run func() ([]cpu.InfoStat, error)) *MockCPUInfoProvider_Info_Call {
	_c.Call.Return(run)
	return _c
}

// Percent provides a mock function with given fields: interval, perCPU
func (_m *MockCPUInfoProvider) Percent(interval time.Duration, perCPU bool) ([]float64, error) {
	ret := _m.Called(interval, perCPU)

	if len(ret) == 0 {
		panic("no return value specified for Percent")
	}

	var r0 []float64
	var r1 error
	if rf, ok := ret.Get(0).(func(time.Duration, bool) ([]float64, error)); ok {
		return rf(interval, perCPU)
	}
	if rf, ok := ret.Get(0).(func(time.Duration, bool) []float64); ok {
		r0 = rf(interval, perCPU)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float64)
		}
	}

	if rf, ok := ret.Get(1).(func(time.Duration, bool) error); ok {
		r1 = rf(interval, perCPU)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCPUInfoProvider_Percent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Percent'
type MockCPUInfoProvider_Percent_Call struct {
	*mock.Call
}

// Percent is a helper method to define mock.On call
//   - interval time.Duration
//   - perCPU bool
func (_e *MockCPUInfoProvider_Expecter) Percent(interval interface{}, perCPU interface{}) *MockCPUInfoProvider_Percent_Call {
	return &MockCPUInfoProvider_Percent_Call{Call: _e.mock.On("Percent", interval, perCPU)}
}

func (_c *MockCPUInfoProvider_Percent_Call) Run(run func(interval time.Duration, perCPU bool)) *MockCPUInfoProvider_Percent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Duration), args[1].(bool))
	})
	return _c
}

func (_c *MockCPUInfoProvider_Percent_Call) Return(_a0 []float64, _a1 error) *MockCPUInfoProvider_Percent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCPUInfoProvider_Percent_Call) RunAndReturn(run func(time.Duration, bool) ([]float64, error)) *MockCPUInfoProvider_Percent_Call {
	_c.Call.Return(run)
	return _c
}

// Times provides a mock function with given fields: perCPU
func (_m *MockCPUInfoProvider) Times(perCPU bool) ([]cpu.TimesStat, error) {
	ret := _m.Called(perCPU)

	if len(ret) == 0 {
		panic("no return value specified for Times")
	}

	var r0 []cpu.TimesStat
	var r1 error
	if rf, ok := ret.Get(0).(func(bool) ([]cpu.TimesStat, error)); ok {
		return rf(perCPU)
	}
	if rf, ok := ret.Get(0).(func(bool) []cpu.TimesStat); ok {
		r0 = rf(perCPU)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]cpu.TimesStat)
		}
	}

	if rf, ok := ret.Get(1).(func(bool) error); ok {
		r1 = rf(perCPU)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCPUInfoProvider_Times_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Times'
type MockCPUInfoProvider_Times_Call struct {
	*mock.Call
}

// Times is a helper method to define mock.On call
//   - perCPU bool
func (_e *MockCPUInfoProvider_Expecter) Times(perCPU interface{}) *MockCPUInfoProvider_Times_Call {
	return &MockCPUInfoProvider_Times_Call{Call: _e.mock.On("Times", perCPU)}
}

func (_c *MockCPUInfoProvider_Times_Call) Run(run func(perCPU bool)) *MockCPUInfoProvider_Times_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool))
	})
	return _c
}

func (_c *MockCPUInfoProvider_Times_Call) Return(_a0 []cpu.TimesStat, _a1 error) *MockCPUInfoProvider_Times_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCPUInfoProvider_Times_Call) RunAndReturn(run func(bool) ([]cpu.TimesStat, error)) *MockCPUInfoProvider_Times_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCPUInfoProvider creates a new instance of MockCPUInfoProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCPUInfoProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCPUInfoProvider {
	mock := &MockCPUInfoProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
