// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	fs "io/fs"

	mock "github.com/stretchr/testify/mock"
)

// MockFileSystem is an autogenerated mock type for the FileSystem type
type MockFileSystem struct {
	mock.Mock
}

type MockFileSystem_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileSystem) EXPECT() *MockFileSystem_Expecter {
	return &MockFileSystem_Expecter{mock: &_m.Mock}
}

// ReadDir provides a mock function with given fields: name
func (_m *MockFileSystem) ReadDir(name string) ([]fs.DirEntry, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for ReadDir")
	}

	var r0 []fs.DirEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]fs.DirEntry, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) []fs.DirEntry); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]fs.DirEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFileSystem_ReadDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadDir'
type MockFileSystem_ReadDir_Call struct {
	*mock.Call
}

// ReadDir is a helper method to define mock.On call
//   - name string
func (_e *MockFileSystem_Expecter) ReadDir(name interface{}) *MockFileSystem_ReadDir_Call {
	return &MockFileSystem_ReadDir_Call{Call: _e.mock.On("ReadDir", name)}
}

func (_c *MockFileSystem_ReadDir_Call) Run(run func(name string)) *MockFileSystem_ReadDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockFileSystem_ReadDir_Call) Return(_a0 []fs.DirEntry, _a1 error) *MockFileSystem_ReadDir_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFileSystem_ReadDir_Call) RunAndReturn(run func(string) ([]fs.DirEntry, error)) *MockFileSystem_ReadDir_Call {
	_c.Call.Return(run)
	return _c
}

// ReadFile provides a mock function with given fields: name
func (_m *MockFileSystem) ReadFile(name string) ([]byte, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for ReadFile")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFileSystem_ReadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadFile'
type MockFileSystem_ReadFile_Call struct {
	*mock.Call
}

// ReadFile is a helper method to define mock.On call
//   - name string
func (_e *MockFileSystem_Expecter) ReadFile(name interface{}) *MockFileSystem_ReadFile_Call {
	return &MockFileSystem_ReadFile_Call{Call: _e.mock.On("ReadFile", name)}
}

func (_c *MockFileSystem_ReadFile_Call) Run(run func(name string)) *MockFileSystem_ReadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockFileSystem_ReadFile_Call) Return(_a0 []byte, _a1 error) *MockFileSystem_ReadFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFileSystem_ReadFile_Call) RunAndReturn(run func(string) ([]byte, error)) *MockFileSystem_ReadFile_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function with given fields: name
func (_m *MockFileSystem) Stat(name string) (fs.FileInfo, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 fs.FileInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (fs.FileInfo, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) fs.FileInfo); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fs.FileInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFileSystem_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type MockFileSystem_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - name string
func (_e *MockFileSystem_Expecter) Stat(name interface{}) *MockFileSystem_Stat_Call {
	return &MockFileSystem_Stat_Call{Call: _e.mock.On("Stat", name)}
}

func (_c *MockFileSystem_Stat_Call) Run(run func(name string)) *MockFileSystem_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockFileSystem_Stat_Call) Return(_a0 fs.FileInfo, _a1 error) *MockFileSystem_Stat_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFileSystem_Stat_Call) RunAndReturn(run func(string) (fs.FileInfo, error)) *MockFileSystem_Stat_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFileSystem creates a new instance of MockFileSystem. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileSystem(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileSystem {
	mock := &MockFileSystem{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
