// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mem "github.com/shirou/gopsutil/v4/mem"
	mock "github.com/stretchr/testify/mock"
)

// MockMemoryInfoProvider is an autogenerated mock type for the MemoryInfoProvider type
type MockMemoryInfoProvider struct {
	mock.Mock
}

type MockMemoryInfoProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMemoryInfoProvider) EXPECT() *MockMemoryInfoProvider_Expecter {
	return &MockMemoryInfoProvider_Expecter{mock: &_m.Mock}
}

// SwapMemory provides a mock function with no fields
func (_m *MockMemoryInfoProvider) SwapMemory() (*mem.SwapMemoryStat, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SwapMemory")
	}

	var r0 *mem.SwapMemoryStat
	var r1 error
	if rf, ok := ret.Get(0).(func() (*mem.SwapMemoryStat, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *mem.SwapMemoryStat); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mem.SwapMemoryStat)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMemoryInfoProvider_SwapMemory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SwapMemory'
type MockMemoryInfoProvider_SwapMemory_Call struct {
	*mock.Call
}

// SwapMemory is a helper method to define mock.On call
func (_e *MockMemoryInfoProvider_Expecter) SwapMemory() *MockMemoryInfoProvider_SwapMemory_Call {
	return &MockMemoryInfoProvider_SwapMemory_Call{Call: _e.mock.On("SwapMemory")}
}

func (_c *MockMemoryInfoProvider_SwapMemory_Call) Run(run func()) *MockMemoryInfoProvider_SwapMemory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMemoryInfoProvider_SwapMemory_Call) Return(_a0 *mem.SwapMemoryStat, _a1 error) *MockMemoryInfoProvider_SwapMemory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMemoryInfoProvider_SwapMemory_Call) RunAndReturn(run func() (*mem.SwapMemoryStat, error)) *MockMemoryInfoProvider_SwapMemory_Call {
	_c.Call.Return(run)
	return _c
}

// VirtualMemory provides a mock function with no fields
func (_m *MockMemoryInfoProvider) VirtualMemory() (*mem.VirtualMemoryStat, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for VirtualMemory")
	}

	var r0 *mem.VirtualMemoryStat
	var r1 error
	if rf, ok := ret.Get(0).(func() (*mem.VirtualMemoryStat, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *mem.VirtualMemoryStat); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mem.VirtualMemoryStat)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMemoryInfoProvider_VirtualMemory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VirtualMemory'
type MockMemoryInfoProvider_VirtualMemory_Call struct {
	*mock.Call
}

// VirtualMemory is a helper method to define mock.On call
func (_e *MockMemoryInfoProvider_Expecter) VirtualMemory() *MockMemoryInfoProvider_VirtualMemory_Call {
	return &MockMemoryInfoProvider_VirtualMemory_Call{Call: _e.mock.On("VirtualMemory")}
}

func (_c *MockMemoryInfoProvider_VirtualMemory_Call) Run(run func()) *MockMemoryInfoProvider_VirtualMemory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMemoryInfoProvider_VirtualMemory_Call) Return(_a0 *mem.VirtualMemoryStat, _a1 error) *MockMemoryInfoProvider_VirtualMemory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMemoryInfoProvider_VirtualMemory_Call) RunAndReturn(run func() (*mem.VirtualMemoryStat, error)) *MockMemoryInfoProvider_VirtualMemory_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMemoryInfoProvider creates a new instance of MockMemoryInfoProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMemoryInfoProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMemoryInfoProvider {
	mock := &MockMemoryInfoProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
