// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	host "github.com/shirou/gopsutil/v4/host"
	mock "github.com/stretchr/testify/mock"

	sensors "github.com/shirou/gopsutil/v4/sensors"
)

// MockHostInfoProvider is an autogenerated mock type for the HostInfoProvider type
type MockHostInfoProvider struct {
	mock.Mock
}

type MockHostInfoProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHostInfoProvider) EXPECT() *MockHostInfoProvider_Expecter {
	return &MockHostInfoProvider_Expecter{mock: &_m.Mock}
}

// Info provides a mock function with no fields
func (_m *MockHostInfoProvider) Info() (*host.InfoStat, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Info")
	}

	var r0 *host.InfoStat
	var r1 error
	if rf, ok := ret.Get(0).(func() (*host.InfoStat, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *host.InfoStat); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*host.InfoStat)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHostInfoProvider_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockHostInfoProvider_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
func (_e *MockHostInfoProvider_Expecter) Info() *MockHostInfoProvider_Info_Call {
	return &MockHostInfoProvider_Info_Call{Call: _e.mock.On("Info")}
}

func (_c *MockHostInfoProvider_Info_Call) Run(run func()) *MockHostInfoProvider_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHostInfoProvider_Info_Call) Return(_a0 *host.InfoStat, _a1 error) *MockHostInfoProvider_Info_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHostInfoProvider_Info_Call) RunAndReturn(run func() (*host.InfoStat, error)) *MockHostInfoProvider_Info_Call {
	_c.Call.Return(run)
	return _c
}

// SensorsTemperatures provides a mock function with no fields
func (_m *MockHostInfoProvider) SensorsTemperatures() ([]sensors.TemperatureStat, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SensorsTemperatures")
	}

	var r0 []sensors.TemperatureStat
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]sensors.TemperatureStat, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []sensors.TemperatureStat); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sensors.TemperatureStat)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHostInfoProvider_SensorsTemperatures_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SensorsTemperatures'
type MockHostInfoProvider_SensorsTemperatures_Call struct {
	*mock.Call
}

// SensorsTemperatures is a helper method to define mock.On call
func (_e *MockHostInfoProvider_Expecter) SensorsTemperatures() *MockHostInfoProvider_SensorsTemperatures_Call {
	return &MockHostInfoProvider_SensorsTemperatures_Call{Call: _e.mock.On("SensorsTemperatures")}
}

func (_c *MockHostInfoProvider_SensorsTemperatures_Call) Run(run func()) *MockHostInfoProvider_SensorsTemperatures_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHostInfoProvider_SensorsTemperatures_Call) Return(_a0 []sensors.TemperatureStat, _a1 error) *MockHostInfoProvider_SensorsTemperatures_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHostInfoProvider_SensorsTemperatures_Call) RunAndReturn(run func() ([]sensors.TemperatureStat, error)) *MockHostInfoProvider_SensorsTemperatures_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHostInfoProvider creates a new instance of MockHostInfoProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHostInfoProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHostInfoProvider {
	mock := &MockHostInfoProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
