// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	load "github.com/shirou/gopsutil/v4/load"
	mock "github.com/stretchr/testify/mock"
)

// MockLoadInfoProvider is an autogenerated mock type for the LoadInfoProvider type
type MockLoadInfoProvider struct {
	mock.Mock
}

type MockLoadInfoProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoadInfoProvider) EXPECT() *MockLoadInfoProvider_Expecter {
	return &MockLoadInfoProvider_Expecter{mock: &_m.Mock}
}

// Avg provides a mock function with no fields
func (_m *MockLoadInfoProvider) Avg() (*load.AvgStat, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Avg")
	}

	var r0 *load.AvgStat
	var r1 error
	if rf, ok := ret.Get(0).(func() (*load.AvgStat, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *load.AvgStat); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*load.AvgStat)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLoadInfoProvider_Avg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Avg'
type MockLoadInfoProvider_Avg_Call struct {
	*mock.Call
}

// Avg is a helper method to define mock.On call
func (_e *MockLoadInfoProvider_Expecter) Avg() *MockLoadInfoProvider_Avg_Call {
	return &MockLoadInfoProvider_Avg_Call{Call: _e.mock.On("Avg")}
}

func (_c *MockLoadInfoProvider_Avg_Call) Run(run func()) *MockLoadInfoProvider_Avg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLoadInfoProvider_Avg_Call) Return(_a0 *load.AvgStat, _a1 error) *MockLoadInfoProvider_Avg_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLoadInfoProvider_Avg_Call) RunAndReturn(run func() (*load.AvgStat, error)) *MockLoadInfoProvider_Avg_Call {
	_c.Call.Return(run)
	return _c
}

// Misc provides a mock function with no fields
func (_m *MockLoadInfoProvider) Misc() (*load.MiscStat, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Misc")
	}

	var r0 *load.MiscStat
	var r1 error
	if rf, ok := ret.Get(0).(func() (*load.MiscStat, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *load.MiscStat); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*load.MiscStat)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLoadInfoProvider_Misc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Misc'
type MockLoadInfoProvider_Misc_Call struct {
	*mock.Call
}

// Misc is a helper method to define mock.On call
func (_e *MockLoadInfoProvider_Expecter) Misc() *MockLoadInfoProvider_Misc_Call {
	return &MockLoadInfoProvider_Misc_Call{Call: _e.mock.On("Misc")}
}

func (_c *MockLoadInfoProvider_Misc_Call) Run(run func()) *MockLoadInfoProvider_Misc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLoadInfoProvider_Misc_Call) Return(_a0 *load.MiscStat, _a1 error) *MockLoadInfoProvider_Misc_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLoadInfoProvider_Misc_Call) RunAndReturn(run func() (*load.MiscStat, error)) *MockLoadInfoProvider_Misc_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLoadInfoProvider creates a new instance of MockLoadInfoProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoadInfoProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoadInfoProvider {
	mock := &MockLoadInfoProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
