// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/shirou/gopsutil/v4/net"
	mock "github.com/stretchr/testify/mock"
)

// NewMockNetworkInfoProvider creates a new instance of MockNetworkInfoProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNetworkInfoProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNetworkInfoProvider {
	mock := &MockNetworkInfoProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNetworkInfoProvider is an autogenerated mock type for the NetworkInfoProvider type
type MockNetworkInfoProvider struct {
	mock.Mock
}

type MockNetworkInfoProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNetworkInfoProvider) EXPECT() *MockNetworkInfoProvider_Expecter {
	return &MockNetworkInfoProvider_Expecter{mock: &_m.Mock}
}

// IOCounters provides a mock function for the type MockNetworkInfoProvider
func (_mock *MockNetworkInfoProvider) IOCounters(pernic bool) ([]net.IOCountersStat, error) {
	ret := _mock.Called(pernic)

	if len(ret) == 0 {
		panic("no return value specified for IOCounters")
	}

	var r0 []net.IOCountersStat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(bool) ([]net.IOCountersStat, error)); ok {
		return returnFunc(pernic)
	}
	if returnFunc, ok := ret.Get(0).(func(bool) []net.IOCountersStat); ok {
		r0 = returnFunc(pernic)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]net.IOCountersStat)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(bool) error); ok {
		r1 = returnFunc(pernic)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNetworkInfoProvider_IOCounters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IOCounters'
type MockNetworkInfoProvider_IOCounters_Call struct {
	*mock.Call
}

// IOCounters is a helper method to define mock.On call
//   - pernic bool
func (_e *MockNetworkInfoProvider_Expecter) IOCounters(pernic any) *MockNetworkInfoProvider_IOCounters_Call {
	return &MockNetworkInfoProvider_IOCounters_Call{Call: _e.mock.On("IOCounters", pernic)}
}

func (_c *MockNetworkInfoProvider_IOCounters_Call) Run(run func(pernic bool)) *MockNetworkInfoProvider_IOCounters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNetworkInfoProvider_IOCounters_Call) Return(iOCountersStats []net.IOCountersStat, err error) *MockNetworkInfoProvider_IOCounters_Call {
	_c.Call.Return(iOCountersStats, err)
	return _c
}

func (_c *MockNetworkInfoProvider_IOCounters_Call) RunAndReturn(run func(pernic bool) ([]net.IOCountersStat, error)) *MockNetworkInfoProvider_IOCounters_Call {
	_c.Call.Return(run)
	return _c
}

// Interfaces provides a mock function for the type MockNetworkInfoProvider
func (_mock *MockNetworkInfoProvider) Interfaces() ([]net.InterfaceStat, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Interfaces")
	}

	var r0 []net.InterfaceStat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]net.InterfaceStat, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []net.InterfaceStat); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]net.InterfaceStat)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNetworkInfoProvider_Interfaces_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Interfaces'
type MockNetworkInfoProvider_Interfaces_Call struct {
	*mock.Call
}

// Interfaces is a helper method to define mock.On call
func (_e *MockNetworkInfoProvider_Expecter) Interfaces() *MockNetworkInfoProvider_Interfaces_Call {
	return &MockNetworkInfoProvider_Interfaces_Call{Call: _e.mock.On("Interfaces")}
}

func (_c *MockNetworkInfoProvider_Interfaces_Call) Run(run func()) *MockNetworkInfoProvider_Interfaces_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNetworkInfoProvider_Interfaces_Call) Return(interfaceStats []net.InterfaceStat, err error) *MockNetworkInfoProvider_Interfaces_Call {
	_c.Call.Return(interfaceStats, err)
	return _c
}

func (_c *MockNetworkInfoProvider_Interfaces_Call) RunAndReturn(run func() ([]net.InterfaceStat, error)) *MockNetworkInfoProvider_Interfaces_Call {
	_c.Call.Return(run)
	return _c
}
