// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/shirou/gopsutil/v4/disk"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDiskInfoProvider creates a new instance of MockDiskInfoProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDiskInfoProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDiskInfoProvider {
	mock := &MockDiskInfoProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDiskInfoProvider is an autogenerated mock type for the DiskInfoProvider type
type MockDiskInfoProvider struct {
	mock.Mock
}

type MockDiskInfoProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDiskInfoProvider) EXPECT() *MockDiskInfoProvider_Expecter {
	return &MockDiskInfoProvider_Expecter{mock: &_m.Mock}
}

// IOCounters provides a mock function for the type MockDiskInfoProvider
func (_mock *MockDiskInfoProvider) IOCounters() (map[string]disk.IOCountersStat, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IOCounters")
	}

	var r0 map[string]disk.IOCountersStat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (map[string]disk.IOCountersStat, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() map[string]disk.IOCountersStat); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]disk.IOCountersStat)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDiskInfoProvider_IOCounters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IOCounters'
type MockDiskInfoProvider_IOCounters_Call struct {
	*mock.Call
}

// IOCounters is a helper method to define mock.On call
func (_e *MockDiskInfoProvider_Expecter) IOCounters() *MockDiskInfoProvider_IOCounters_Call {
	return &MockDiskInfoProvider_IOCounters_Call{Call: _e.mock.On("IOCounters")}
}

func (_c *MockDiskInfoProvider_IOCounters_Call) Run(run func()) *MockDiskInfoProvider_IOCounters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDiskInfoProvider_IOCounters_Call) Return(stringToIOCountersStat map[string]disk.IOCountersStat, err error) *MockDiskInfoProvider_IOCounters_Call {
	_c.Call.Return(stringToIOCountersStat, err)
	return _c
}

func (_c *MockDiskInfoProvider_IOCounters_Call) RunAndReturn(run func() (map[string]disk.IOCountersStat, error)) *MockDiskInfoProvider_IOCounters_Call {
	_c.Call.Return(run)
	return _c
}

// Partitions provides a mock function for the type MockDiskInfoProvider
func (_mock *MockDiskInfoProvider) Partitions(all bool) ([]disk.PartitionStat, error) {
	ret := _mock.Called(all)

	if len(ret) == 0 {
		panic("no return value specified for Partitions")
	}

	var r0 []disk.PartitionStat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(bool) ([]disk.PartitionStat, error)); ok {
		return returnFunc(all)
	}
	if returnFunc, ok := ret.Get(0).(func(bool) []disk.PartitionStat); ok {
		r0 = returnFunc(all)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]disk.PartitionStat)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(bool) error); ok {
		r1 = returnFunc(all)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDiskInfoProvider_Partitions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Partitions'
type MockDiskInfoProvider_Partitions_Call struct {
	*mock.Call
}

// Partitions is a helper method to define mock.On call
//   - all bool
func (_e *MockDiskInfoProvider_Expecter) Partitions(all any) *MockDiskInfoProvider_Partitions_Call {
	return &MockDiskInfoProvider_Partitions_Call{Call: _e.mock.On("Partitions", all)}
}

func (_c *MockDiskInfoProvider_Partitions_Call) Run(run func(all bool)) *MockDiskInfoProvider_Partitions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDiskInfoProvider_Partitions_Call) Return(partitionStats []disk.PartitionStat, err error) *MockDiskInfoProvider_Partitions_Call {
	_c.Call.Return(partitionStats, err)
	return _c
}

func (_c *MockDiskInfoProvider_Partitions_Call) RunAndReturn(run func(all bool) ([]disk.PartitionStat, error)) *MockDiskInfoProvider_Partitions_Call {
	_c.Call.Return(run)
	return _c
}

// Usage provides a mock function for the type MockDiskInfoProvider
func (_mock *MockDiskInfoProvider) Usage(path string) (*disk.UsageStat, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Usage")
	}

	var r0 *disk.UsageStat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*disk.UsageStat, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *disk.UsageStat); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*disk.UsageStat)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDiskInfoProvider_Usage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Usage'
type MockDiskInfoProvider_Usage_Call struct {
	*mock.Call
}

// Usage is a helper method to define mock.On call
//   - path string
func (_e *MockDiskInfoProvider_Expecter) Usage(path any) *MockDiskInfoProvider_Usage_Call {
	return &MockDiskInfoProvider_Usage_Call{Call: _e.mock.On("Usage", path)}
}

func (_c *MockDiskInfoProvider_Usage_Call) Run(run func(path string)) *MockDiskInfoProvider_Usage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDiskInfoProvider_Usage_Call) Return(usageStat *disk.UsageStat, err error) *MockDiskInfoProvider_Usage_Call {
	_c.Call.Return(usageStat, err)
	return _c
}

func (_c *MockDiskInfoProvider_Usage_Call) RunAndReturn(run func(path string) (*disk.UsageStat, error)) *MockDiskInfoProvider_Usage_Call {
	_c.Call.Return(run)
	return _c
}
