// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	process "github.com/shirou/gopsutil/v4/process"
	mock "github.com/stretchr/testify/mock"
)

// MockProcessInfoProvider is an autogenerated mock type for the ProcessInfoProvider type
type MockProcessInfoProvider struct {
	mock.Mock
}

type MockProcessInfoProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProcessInfoProvider) EXPECT() *MockProcessInfoProvider_Expecter {
	return &MockProcessInfoProvider_Expecter{mock: &_m.Mock}
}

// NewProcess provides a mock function with given fields: pid
func (_m *MockProcessInfoProvider) NewProcess(pid int32) (*process.Process, error) {
	ret := _m.Called(pid)

	if len(ret) == 0 {
		panic("no return value specified for NewProcess")
	}

	var r0 *process.Process
	var r1 error
	if rf, ok := ret.Get(0).(func(int32) (*process.Process, error)); ok {
		return rf(pid)
	}
	if rf, ok := ret.Get(0).(func(int32) *process.Process); ok {
		r0 = rf(pid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*process.Process)
		}
	}

	if rf, ok := ret.Get(1).(func(int32) error); ok {
		r1 = rf(pid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProcessInfoProvider_NewProcess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewProcess'
type MockProcessInfoProvider_NewProcess_Call struct {
	*mock.Call
}

// NewProcess is a helper method to define mock.On call
//   - pid int32
func (_e *MockProcessInfoProvider_Expecter) NewProcess(pid interface{}) *MockProcessInfoProvider_NewProcess_Call {
	return &MockProcessInfoProvider_NewProcess_Call{Call: _e.mock.On("NewProcess", pid)}
}

func (_c *MockProcessInfoProvider_NewProcess_Call) Run(run func(pid int32)) *MockProcessInfoProvider_NewProcess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int32))
	})
	return _c
}

func (_c *MockProcessInfoProvider_NewProcess_Call) Return(_a0 *process.Process, _a1 error) *MockProcessInfoProvider_NewProcess_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProcessInfoProvider_NewProcess_Call) RunAndReturn(run func(int32) (*process.Process, error)) *MockProcessInfoProvider_NewProcess_Call {
	_c.Call.Return(run)
	return _c
}

// Processes provides a mock function with no fields
func (_m *MockProcessInfoProvider) Processes() ([]*process.Process, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Processes")
	}

	var r0 []*process.Process
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*process.Process, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*process.Process); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*process.Process)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProcessInfoProvider_Processes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Processes'
type MockProcessInfoProvider_Processes_Call struct {
	*mock.Call
}

// Processes is a helper method to define mock.On call
func (_e *MockProcessInfoProvider_Expecter) Processes() *MockProcessInfoProvider_Processes_Call {
	return &MockProcessInfoProvider_Processes_Call{Call: _e.mock.On("Processes")}
}

func (_c *MockProcessInfoProvider_Processes_Call) Run(run func()) *MockProcessInfoProvider_Processes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProcessInfoProvider_Processes_Call) Return(_a0 []*process.Process, _a1 error) *MockProcessInfoProvider_Processes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProcessInfoProvider_Processes_Call) RunAndReturn(run func() ([]*process.Process, error)) *MockProcessInfoProvider_Processes_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProcessInfoProvider creates a new instance of MockProcessInfoProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProcessInfoProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProcessInfoProvider {
	mock := &MockProcessInfoProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
